# Generated by Django 3.1.7 on 2021-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantfield',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
