# Generated by Django 3.1.7 on 2021-03-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('product', '0002_auto_20210311_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypr',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
