# Generated by Django 3.1.7 on 2021-04-25 09:28

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailimages', '0022_uploadedimage'),
        ('product', '0004_remove_productdetailpage_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryPr',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='productdetailpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='product.ProductTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
