# Generated by Django 3.1.7 on 2021-03-27 00:16

from django.db import migrations
import home.block
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', home.block.APIRichTextBlock())]),
        ),
    ]
