# Generated by Django 3.1.7 on 2021-03-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_categorypr_icon'),
        ('home', '0003_auto_20210328_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='product.categorypr'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='product.categorypr'),
        ),
    ]
