# Generated by Django 3.1.7 on 2021-03-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210331_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorybanner',
            old_name='content',
            new_name='content_cat',
        ),
    ]
